### ISSUE TITLE
1.18.2 have error for entity

### ISSUE THREAD

**Issue by antasetyawan** [itsfergydanny/MineableSpawners#87]
[10:00:22 ERROR]: Could not pass event BlockPlaceEvent to MineableSpawners v3.1.2
java.lang.NoClassDefFoundError: Could not initialize class com.dnyferguson.mineablespawners.nbtapi.NBTReflectionUtil
        at com.dnyferguson.mineablespawners.nbtapi.NBTCompound.hasKey(NBTCompound.java:514) ~[MineableSpawners-3.1.2.jar:?]
        at com.dnyferguson.mineablespawners.api.API.getEntityTypeFromItemStack(API.java:29) ~[MineableSpawners-3.1.2.jar:?]
        at com.dnyferguson.mineablespawners.listeners.SpawnerPlaceListener.onSpawnerPlace(SpawnerPlaceListener.java:61) ~[MineableSpawners-3.1.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor130.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-220]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:393) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:383) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:614) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1842) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1387) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1364) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1357) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1335) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[paper-1.18.2.jar:git-Paper-220]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-220]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by thiagogebrimm** [comment]
Same problem :(
